- copy:
    src: ../files/apache/htdocs/
    dest: /ecs/htdocs

- shell: /usr/local/bin/credstash -r eu-west-1 get freeipa/system_user
  register: credstash_system_user
  ignore_errors: yes

- shell:  sudo sysctl -w vm.max_map_count=262144

- name: Configure httpd.conf
  template:
    src: 'httpd-ldap.conf.j2'
    dest: '/ecs/conf.d/httpd-ldap.conf'
    group: 'root'
    owner: 'root'
    mode: '0644'

# Install Filebeat

- shell: curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.1.3-x86_64.rpm
- yum:
   name: filebeat-6.1.3-x86_64.rpm
   state: present

- copy:
    src: ../files/filebeat/filebeat.yml
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: 0600

- service:
    name: filebeat
    state: restarted

# add dd-agent to docker group

- shell: usermod -aG docker dd-agent
- shell: usermod -aG root dd-agent
