- copy:
    src: ../files/apache/htdocs/
    dest: /ecs/htdocs

- shell: /usr/local/bin/credstash -r eu-west-1 get freeipa/system_user
  register: credstash_system_user
  ignore_errors: yes

- shell:  sudo sysctl -w vm.max_map_count=262144

- name: Configure httpd.conf
  template:
    src: 'httpd-ldap.conf.j2'
    dest: '/ecs/conf.d/httpd-ldap.conf'
    group: 'root'
    owner: 'root'
    mode: '0644'
