- copy:
    src: /var/lib/go-agent/pipelines/base/elkstack/files/apache/htdocs/
    dest: /ecs/htdocs

- copy:
    src: /var/lib/go-agent/pipelines/base/elkstack/files/apache/conf/
    dest: /ecs/conf
