- file:
    path: /ecs/conf.d
    state: directory

- copy:
    src: ../files/apache/htdocs/
    dest: /ecs/htdocs

- shell: /usr/local/bin/credstash -r eu-west-1 get freeipa/system_user
  register: credstash_system_user
  ignore_errors: yes

- shell:  sudo sysctl -w vm.max_map_count=262144

- name: Configure httpd.conf
  template:
    src: 'httpd-ldap.conf.j2'
    dest: '/ecs/conf.d/httpd-ldap.conf'
    group: 'root'
    owner: 'root'
    mode: '0644'

# Install Filebeat

- shell: wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
- name: Add Elasticsearch repository
  shell: echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-6.x.list
  args:
    creates: /etc/apt/sources.list.d/elastic-6.x.list
- shell: apt update

- name: install Filebeat
  package:
    name: filebeat
    state: latest

- copy:
    src: ../files/filebeat/filebeat.yml
    dest: /etc/filebeat/filebeat.yml
    owner: root
    group: root
    mode: 0600


- service:
    name: filebeat
    state: restarted
