filebeat.prospectors:
- type: log
  enabled: true
  paths:
    - /var/log/*.log
    - /var/log/datadog/*.log
    - /var/log/messages
    - '/var/lib/docker/containers/*/*.log'
  exclude_files: ['/var/log/yum.log']
  json.message_key: log
  json.add_error_key: true
  json.keys_under_root: true
  processors:
    - add_docker_metadata:
        host: "unix:///var/run/docker.sock"
    - add_cloud_metadata: ~
    - add_locale: ~
  multiline.pattern: "^\t|^[[:space:]]+(at|...)|^Caused by:"
  multiline.match: after
#============================== Dashboards =====================================
  setup.dashboards.enabled: true
  setup.kibana:
    host: "elkstack-common.parliament.uk"

#==========================  Modules configuration ============================
filebeat.modules:

#------------------------------- System Module -------------------------------
- module: system
  # Syslog
  syslog:
    enabled: true
    var.paths: ["/var/log/syslog*"]
  auth:
    enabled: true
    var.paths: ["/var/log/auth.log*"]

output.logstash:
  enabled: true
  hosts: ["internal-logstash-elb-1601667298.eu-west-1.elb.amazonaws.com:5044"]
  worker: 1
  index: 'filebeaat'
  compression_level: 3
