filebeat.prospectors:
- type: log
  enabled: true
  paths:
    - /var/log/*.log
    - /var/log/datadog/*.log
    - /var/log/messages
  exclude_files: ['/var/log/yum.log']

  #========================== Filebeat autodiscover ==============================

# Autodiscover allows you to detect changes in the system and spawn new modules
# or prospectors as they happen.

filebeat.autodiscover:
  # List of enabled autodiscover providers
  providers:
    - type: docker
      templates:
        - condition:
            equals.docker.container.image: 438271037918.dkr.ecr.eu-west-1.amazonaws.com/*
          config:
            - type: log
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log

output.logstash:
  enabled: true
  hosts: ["internal-logstash-elb-1601667298.eu-west-1.elb.amazonaws.com:5044"]
  worker: 1
  index: 'filebeaat'
  compression_level: 3
