filebeat.prospectors:
- type: log
  enabled: true
  paths:
    - /var/log/*.log
    - /var/log/datadog/*.log
    - /var/log/messages
  exclude_files: ['/var/log/yum.log']

- type: docker
  enabled: true
  paths:
    - /var/lib/docker/containers/${data.docker.container.id}/*.log

  setup.kibana:
    host: "elkstack-common.parliament.uk"

  

output.logstash:
  enabled: true
  hosts: ["internal-logstash-elb-1601667298.eu-west-1.elb.amazonaws.com:5044"]
  worker: 1
  index: 'filebeaat'
  compression_level: 3
