filebeat.prospectors:
- type: log
  enabled: true
  paths:
    - /var/log/*.log
    - /var/log/datadog/*.log
    - /var/log/messages
  exclude_files: ['/var/log/yum.log']

output.logstash:
  hosts: ["internal-logstash-elb-1601667298.eu-west-1.elb.amazonaws.com:5044"]
