- hosts: common-nginx-proxy-1
  user: deployer
  become: yes
  become_method: sudo
  vars:
    nginx_sites:
      gocd-common:
        domains: ['gocd-common.parliament.uk']
        upstreams:
          - name: 'gocd-common'
            servers: ['172.16.40.70:8153']
      gocd-pdswebops:
        domains: ['gocd-pdswebops.parliament.uk']
        default_server: True
        upstreams:
          - name: 'gocd-pdswebops'
            servers: ['172.16.248.149:8153']
      gocd-web1devci:
        domains: ['gocd-webdevci.parliament.uk']
        upstreams:
          - name: 'gocd-webdevci'
            servers: ['172.16.128.57:8153']
      gocd-web1live:
        domains: ['gocd-web1live.parliament.uk']
        upstreams:
          - name: 'gocd-web1live'
            servers: ['172.16.136.236:8153']
      freeipa:
        domains: ['freeipa-access.parliament.uk']
        upstreams:
           - name: 'freeipa-master-1'
             servers: ['172.16.40.168']
      grafana-pdswebops:
        domains: ['grafana-pdswebops.parliament.uk']
        upstreams:
           - name: 'grafana-pdswebops-1'
             servers: ['172.16.248.131']
      grafana-common:
        domains:
          - grafana-common.parliament.uk
          - status-dashboards.parliament.uk
          - grafana-common.pdswebops.org
        upstreams:
          - name: 'grafana-common-1'
            servers:
              - '172.16.40.94'

    proxy_pass_https:
      freeipa:
  roles:
    - role: ansible-nginx
    - role: misc
