- hosts: common-nginx-proxy-1
  user: ubuntu
  become: yes
  become_method: sudo
  vars:
    nginx_sites:
      big-test:
        domains: ['big-test.parliament.uk']
        upstreams:
          - name: 'big-test'
            servers: ['172.16.40.55']
      gocd-common:
        domains: ['gocd-common.parliament.uk']
        upstreams:
          - name: 'gocd-common'
            servers: ['172.16.40.54:8153']
      gocd-pdswebops:
        domains: ['gocd-pdswebops.parliament.uk']
        default_server: True
        upstreams:
          - name: 'gocd-pdswebops'
            servers: ['172.16.248.226:8153']
      gocd-web1devci:
        domains: ['gocd-webdevci.parliament.uk']
        upstreams:
          - name: 'gocd-webdevci'
            servers: ['172.16.128.93:8153']
      gocd-web1live:
        domains: ['gocd-web1live.parliament.uk']
        upstreams:
          - name: 'gocd-web1live'
            servers: ['172.16.136.102:8153']
      freeipa:
        domains: ['freeipa-access.parliament.uk']
        upstreams:
           - name: 'freeipa-master-1'
             servers: ['172.16.40.36']
    proxy_pass_https:
      freeipa:
  roles:
    - role: ansible-nginx
#    - role: misc
