- name: Install freeipa-client
  package:
    name: freeipa-client
    state: latest

- shell: credstash -r eu-west-1 get freeipa/system_user
  register: credstash_freeipa_output
  ignore_errors: yes

- copy:
    src: files/krb5.conf
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644



- shell: ipa-client-install -d -U  -p admin -w {{ freeipa_system_user }} --domain=access.parliament.uk --server=freeipa-access.parliament.uk --mkhomedir --ssh-trust-dns
  args:
    creates: /etc/sssd/sssd.conf
