- name: Install freeipa-client
  package:
    name: freeipa-client
    state: latest

- shell: credstash -r eu-west-1 get freeipa/system_user
  register: credstash_freeipa_output
  ignore_errors: yes

- name: Change default realm in krb5.conf if it exists
  lineinfile:
    regexp: "^default_realm"
    dest: /etc/krb5.conf
    line: "	default_realm = 16.248.180.ACCESS.PARLIAMENT.UK"
    state: present


- shell: ipa-client-install -d -U  -p admin -w {{ freeipa_system_user }} --domain=access.parliament.uk --server=freeipa-access.parliament.uk --mkhomedir --ssh-trust-dns
  args:
    creates: /etc/sssd/sssd.conf

- name: Modify PAM common-session so that user home directory is created on first login
  lineinfile:
    dest: /etc/pam.d/common-session
    line: "session required pam_mkhomedir.so"
    insertbefore: ".end of pam-auth-update config"
    state: present
