- name: Install awscli
  package:
    name: awscli
    state: latest

- name: ECR login
  shell: "$(aws ecr get-login --no-include-email --region eu-west-1)"


# Common
- name: Build the image
  command: docker build -t logspout /var/lib/go-agent/pipelines/elkstack/elkstack/files/logspout

- name: tqg the image
  command: docker tag logspout:latest 337667769842.dkr.ecr.eu-west-1.amazonaws.com/logspout:latest

- name: push the image
  command: docker push 337667769842.dkr.ecr.eu-west-1.amazonaws.com/logspout:latest
