- name: Install ntp
  package:
    name: ntp
    state: latest
- name: Install python-minimal
  package:
    name: python-minimal
    state: latest
- name: Install python-pip
  package:
    name: python-pip
    state: latest
- name: Install python-setuptools
  package:
    name: python-setuptools
    state: latest
- name: Install python-dev
  package:
    name: python-dev
    state: latest
- name: Install build-essential
  package:
    name: build-essential
    state: latest
- name: Install libssl-dev
  package:
    name: libssl-dev
    state: latest
- name: Install libffi-dev
  package:
    name: libffi-dev
    state: latest
- name: Install screen
  package:
    name: screen
    state: latest
- name: Install nano
  package:
    name: nano
    state: latest
- name: Install traceroute
  package:
    name: traceroute
    state: latest
- name: Install iftop
  package:
    name: iftop
    state: latest
- name: Install tree
  package:
    name: tree
    state: latest
- name: Install htop
  package:
    name: htop
    state: latest
- name: Install ncdu
  package:
    name: ncdu
    state: latest
- pip:
    name: credstash

- name:  cleans the local repository of retrieved package files that can no longer be downloaded
  apt:
    autoclean: yes
- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
