---

- hosts: tag_cluster_elasticsearch_cluster
  user: deployer
  become: yes
  become_method: sudo


  roles:
    - role: misc
    - { role: elasticsearch, es_instance_name: "node1", es_heap_size: "4g" }
    - { role: elasticsearch, es_instance_name: "node2", es_heap_size: "4g" }
    - { role: elasticsearch, es_instance_name: "node3", es_heap_size: "4g" }
  vars:
    es_cluster_name: elasticsearch-cluster
