---

- hosts: tag_cluster_elasticsearch_cluster
  user: deployer
  become: yes
  become_method: sudo


  roles:
    - role: misc
    - { role: elasticsearch, es_instance_name: "node1", es_data_dirs: "/mnt/data/elasticsearch", es_log_dir: "/var/log/elasticsearch",
    es_config: {
        node.name: ${HOSTNAME},
        cluster.name: "parliament-cluster",
        discovery.zen.ping.unicast.hosts: "tag_Name_core_elasticsearch_node_1:9300,tag_Name_core_elasticsearch_node_2:9300,tag_Name_core_elasticsearch_node_3:9300",
        http.port: 9200,
        transport.tcp.port: 9300,
        node.data: true,
        node.master: true,
        bootstrap.memory_lock: true,
        }
    }
  vars:
    es_scripts: false
    es_templates: false
    es_version_lock: false
    es_heap_size: 1g
    es_api_port: 9200
    es_plugins:
      - plugin: ingest-geoip
