- copy:
    src: ../files/docker-conf.yaml
    dest: /etc/data-agent/conf.d/docker.d/conf.yaml
    owner: dd-agent
    group: dd-agent
    mode: 0644



- service:
    name: datadog-agent
    state: restarted


- shell: usermod -aG docker dd-agent
- shell: usermod -aG root dd-agent
