- name: Install unzip
  package:
    name: unzip
    state: latest
    
- name: Extract file
  unarchive:
    src: https://releases.hashicorp.com/packer/1.2.2/packer_1.2.2_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: 0775
