- name: Copy network interfaces file
  copy:
    src: files/interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart networking

- name: Copy freeipa-ssl.conf file
  copy:
    src: files/freeipa-ssl.conf
    dest: /etc/apache2/sites-available/freeipa-ssl.conf
    owner: root
    group: root
    mode: 0644


- name: Symlink freeipa-ssl to sites-enabled
  file:
    src: '/etc/apache2/sites-available/freeipa-ssl.conf'
    dest: '/etc/apache2/sites-enabled/freeipa-ssl.conf'
    state: 'link'

  notify:
    - Test apache2 and restart

- name: Generate a Self Signed OpenSSL SSLCertificate
  openssl_certificate:
  path: /etc/ssl/certs/access.common-pds.org.crt
  privatekey_path: /etc/ssl/certs/access.common-pds.org.key
  provider: selfsigned
