- module: apache2
  # Access logs
  access:
    enabled: true
    var.paths: ["/opt/bitnami/apache2/logs/access_log*"]
  # Error logs
  error:
    enabled: true
    var.paths: ["/opt/bitnami/apache2/logs/error_log*"]
    # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    #var.paths:
