- hosts: tag_aws_autoscaling_groupName_ecs_cluster
  user: deployer
  become: yes
  become_method: sudo
  vars:

  roles:
    - role: cluster



- hosts: type_t2_medium
  user: deployer
  become: yes
  become_method: sudo
  vars:

  roles:
    - role: elasticsearch
    - role: apache
    - role: kibana
    - role: logstash
    - role: logspout
