- hosts: tag_aws_autoscaling_groupName_ecs_cluster
  user: deployer
  become: yes
  become_method: sudo
  vars:

  roles:
    - role: cluster



- hosts: tag_Name_core_gocd_agent_ansible_1
  user: deployer
  become: yes
  become_method: sudo
  vars:

  roles:
    - role: ecr
    - role: logspout-web1devci
