- name: Install the ipa-server and ipa-server-dns packages
  vars: 
    inventory_hostname: freeipa-master-1.access.parliament.uk
  yum:
    name: ipa-server
    state: present
    name: ipa-server-dns
    state: present


- name: Run the ipa-server-install command
  command: ipa-server-install -U --setup-dns --hostname=freeipa-master-1.access.parliament.uk --domain={{ domain }} --realm={{ realm }} --ds-password={{ directory_manager_password }} --admin-password={{ principal_user_password }} --forwarder={{ dns_forwarder_1 }} 

