- name: Install the ipa-server and ipa-server-dns packages
  vars:
    inventory_hostname: freeipa-access.parliament.uk
  yum:
    name: ipa-server
    state: present
    name: ipa-server-dns
    state: present

- lineinfile:
    path: /etc/hosts
    regexp: 'freeipa-access.parliament.uk'
    line: '172.16.40.36 freeipa-access.parliament.uk'

- lineinfile:
    path: /etc/hosts
    line: '172.16.40.36 {{inventory_hostname}}'

- name: Run the ipa-server-install command
  command: ipa-server-install -U --setup-dns --hostname=freeipa-access.parliament.uk --domain={{ domain }} --realm={{ realm }} --ds-password={{ directory_manager_password }} --admin-password={{ principal_user_password }} --forwarder={{ dns_forwarder_1 }}
