---

- name: Install role dependencies
  apt:
    name: 'python-passlib'
    state: 'present'

- name: Install apache2
  apt:
    name: 'apache2'
    state: 'present'
  notify:
    - Test apache2 and restart


- name: Create default apache2 directories
  file:
    path: '{{ item }}'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  with_items:
    - '/usr/www/html'
    - '/etc/apache2/sites-available'
    - '/etc/apache2/sites-enabled'
    - '/etc/apache2/mods-available'
    - '/etc/apache2/mods-enabled'
    - '/etc/apache2/conf-available'
    - '/etc/apache2/conf-enabled'


- name: Remove default site
  file:
    path: '{{ item }}'
    state: 'absent'
  with_items:
    - '/var/www/html'
    - '/etc/apache2/sites-enabled/000-default.conf'
    - '/etc/apache2/sites-available/000-default.conf'
  notify:
    - Test apache2 and reload

- name: Configure apache2
  template:
    src: 'etc/apache2/apache2.conf.j2'
    dest: '/etc/apache2/apache2.conf'
    group: 'root'
    owner: 'root'
    mode: '0644'
  register: apache2_register_apache2_config
  notify:
    - Test apache2 and reload
