---

- name: Install role dependencies
  apt:
    name: 'python-passlib'
    state: 'present'

- name: Install apache2
  apt:
    name: 'apache2'
    state: 'present'
  notify:
    - Test apache2 and restart
