---

- name: Install role dependencies
  apt:
    name: 'python-passlib'
    state: 'present'

- name: Install apache2
  apt:
    name: 'apache2'
    state: 'present'
  notify:
    - Test apache2 and restart

- apache2_module:
    state: present
    name: proxy

- apache2_module:
    state: present
    name: proxy_html

- apache2_module:
    state: present
    name: proxy_http

- apache2_module:
    state: present
    name: session

- apache2_module:
    state: present
    name: ldap

- apache2_module:
    state: present
    name: authnz_ldap




- name: Create default apache2 directories
  file:
    path: '{{ item }}'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  with_items:
    - '/var/www/html'
    - '/etc/apache2/sites-available'
    - '/etc/apache2/sites-enabled'
    - '/etc/apache2/mods-available'
    - '/etc/apache2/mods-enabled'
    - '/etc/apache2/conf-available'
    - '/etc/apache2/conf-enabled'


- name: Remove default site
  file:
    path: '{{ item }}'
    state: 'absent'
  with_items:
    - '/var/www/html'
    - '/etc/apache2/sites-enabled/000-default.conf'
    - '/etc/apache2/sites-available/000-default.conf'
  notify:
    - Test apache2 and reload

- name: Configure apache2
  template:
    src: 'etc/apache2/apache2.conf.j2'
    dest: '/etc/apache2/apache2.conf'
    group: 'root'
    owner: 'root'
    mode: '0644'
  register: apache2_register_apache2_config
  notify:
    - Test apache2 and reload

- name: Configure sites-enabled (vhosts)
  template:
    src: 'etc/apache2/sites-available/default.conf.j2'
    dest: '/etc/apache2/sites-available/{{ item.key }}.conf'
    group: 'root'
    owner: 'root'
    mode: '0644'
  with_dict: '{{ apache2_sites }}'
  register: apache2_register_vhost_config
  notify:
    - Test apache2 and reload

- name: Symlink sites-available to sites-enabled
  file:
    src: '/etc/apache2/sites-available/{{ item.key }}.conf'
    dest: '/etc/apache2/sites-enabled/{{ item.key }}.conf'
    state: 'link'
  with_dict: '{{ apache2_sites }}'
  notify:
    - Test apache2 and restart


# Treat elkstack-common separately because it uses load balancing hard-coded to two ecs-nodes

- name: Place elkstack-common conf spearately because it uses load balancing
  template:
    src: 'etc/apache2/sites-available/elkstack-common.conf.j2'
    dest: '/etc/apache2/sites-available/elkstack-common.conf'
    group: 'root'
    owner: 'root'
    mode: '0644'

  register: apache2_register_vhost_config
  notify:
    - Test apache2 and reload

- name: Symlink elkstack-common to sites-enabled
  file:
    src: '/etc/apache2/sites-available/elkstack-common.conf'
    dest: '/etc/apache2/sites-enabled/elkstack-common.conf'
    state: 'link'

  notify:
    - Test apache2 and restart
