- name: Create Directory
  file:
    path: /mnt/data
    state: directory
    owner: root
    group: root

- parted:
    device: /dev/xvdh
    number: 1
    state: present

# Format drive
- filesystem:
    fstype: ext4
    dev: /dev/xvdh1

- name: Mount Directory
  mount:
   path: /mnt/data
   src: /dev/xvdh1
   fstype: ext4
   opts: defaults
   state: mounted


# Configure datadog elasticsearch integration

- copy:
    src: files/elasticsearch.yml
    dest: /etc/dd-agent/conf.d/elasticsearch.yml
    owner: dd-agent
    group: dd-agent
    mode: 0644

- name: restart datadog-agent
  service:
    name: datadog-agent
    state: restarted
  when: datadog_enabled
