- name: Get elastic repository
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Save the repository definition to /etc/apt/sources.list.d/elastic-6.x.list
  shell: echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-6.x.list

- name: install Java 8
  apt:
    name: openjdk-8-jre-headless
    update_cache: yes

- name: Update repositories and install
  apt:
    name: logstash
    update_cache: yes


- copy:
    src: ../files/logstash.yml
    dest: /etc/logstash/logstash.yml
    owner: root
    group: root
    mode: 0644

- copy:
    src: ../files/logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf
    owner: root
    group: root
    mode: 0644

- shell:  /usr/share/logstash/bin/logstash-plugin install logstash-input-sqs && /usr/share/logstash/bin/logstash-plugin install logstash-filter-json &&  /usr/share/logstash/bin/logstash-plugin install logstash-input-gelf && /usr/share/logstash/bin/logstash-plugin install logstash-input-cloudwatch && /usr/share/logstash/bin/logstash-plugin install logstash-input-s3 && /usr/share/logstash/bin/logstash-plugin install logstash-input-cloudwatch_logs

- name: Restart service logstash, in all cases
  service:
    name: logstash
    state: restarted
