---

- name: Install role dependencies
  apt:
    name: 'python-passlib'
    state: 'present'

- name: Install nginx
  apt:
    name: 'nginx'
    state: 'present'
  notify:
    - Test nginx and restart

- name: Install python-LDAP
  apt:
    name: 'python-ldap'
    state: 'present'

- name: Create default nginx directories
  file:
    path: '{{ item }}'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  with_items:
    - '/usr/share/nginx/html'
    - '/etc/nginx/sites-available'
    - '/etc/nginx/sites-enabled'
    - '/etc/nginx/conf.d'
    - '/etc/nginx/ssl'

- name: Remove default site
  file:
    path: '{{ item }}'
    state: 'absent'
  with_items:
    - '/var/www/html'
    - '/etc/nginx/sites-enabled/default'
    - '/etc/nginx/sites-available/default'
  notify:
    - Test nginx and reload
- name: Configure nginx
  template:
    src: 'etc/nginx/nginx.conf.j2'
    dest: '/etc/nginx/nginx.conf'
    group: 'root'
    owner: 'root'
    mode: '0644'
  register: nginx_register_nginx_config
  notify:
    - Test nginx and reload

- name: Configure sites-enabled (vhosts)
  template:
    src: 'etc/nginx/sites-available/default.conf.j2'
    dest: '/etc/nginx/sites-available/{{ item.key }}.conf'
    group: 'root'
    owner: 'root'
    mode: '0644'
  with_dict: '{{ nginx_sites }}'
  register: nginx_register_vhost_config
  notify:
    - Test nginx and reload

- name: Symlink sites-available to sites-enabled
  file:
    src: '/etc/nginx/sites-available/{{ item.key }}.conf'
    dest: '/etc/nginx/sites-enabled/{{ item.key }}.conf'
    state: 'link'
  with_dict: '{{ nginx_sites }}'
  notify:
    - Test nginx and restart

- name: Forcefully restart nginx
  service:
    name: 'nginx'
    state: 'restarted'

# Treat elkstack-common separately because it uses load balancing hard-coded to two ecs-nodes

- name: Place elkstack-common conf spearately because it uses load balancing
  template:
    src: 'etc/nginx/sites-available/elkstack-common.conf.j2'
    dest: '/etc/nginx/sites-available/elkstack-common.conf'
    group: 'root'
    owner: 'root'
    mode: '0644'
  with_dict: '{{ nginx_sites }}'
  register: nginx_register_vhost_config
  notify:
    - Test nginx and reload

- name: Symlink elkstack-common to sites-enabled
  file:
    src: '/etc/nginx/sites-available/elkstack-common.conf'
    dest: '/etc/nginx/sites-enabled/elkstack-common.conf'
    state: 'link'
  with_dict: '{{ nginx_sites }}'
  notify:
    - Test nginx and restart

- name: Place elkstack-test conf spearately because it uses ldap
  template:
    src: 'etc/nginx/sites-available/elkstack-test.conf.j2'
    dest: '/etc/nginx/sites-available/elkstack-test.conf'
    group: 'root'
    owner: 'root'
    mode: '0644'
  with_dict: '{{ nginx_sites }}'
  register: nginx_register_vhost_config
  notify:
    - Test nginx and reload

- name: Symlink elkstack-common to sites-enabled
  file:
    src: '/etc/nginx/sites-available/elkstack-test.conf'
    dest: '/etc/nginx/sites-enabled/elkstack-test.conf'
    state: 'link'
  with_dict: '{{ nginx_sites }}'
  notify:
    - Test nginx and restart
