- name: Create Deployer User
  command: credstash -r eu-west-1 get deployer_id_rsa_pub
  register: deployer_key_pub

- user:
    name: deployer

- file:
    path: /home/deployer/.ssh
    state: directory
    owner: deployer
    group: deployer
    mode: 0700

- file:
    path: /home/deployer/.ssh/authorized_keys
    state: touch
    owner: deployer
    group: deployer

- file:
  path: /etc/sudoers.d/sudoers
  state: touch
  owner: root
  owner: root

- name: Place sudoers rule for deployer users
  shell: echo '# User rules\ndeployer ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/sudoers
  args:
    creates: /etc/sudoers.d/sudoers
