- name: Create Deployer User
  command: credstash -r eu-west-1 get deployer_id_rsa_pub
  register: deployer_key_pub

- user:
    name: deployer

- file:
    path: /home/deployer/.ssh
    state: directory
    owner: deployer
    group: deployer

- name: create authorized_keys
  command: touch /home/deployer/.ssh/authorized_keys

- name: place public key in authorized_keys
  command: echo deployer_key_pub >> /home/deployer/.ssh/authorized_keys
