- name: Create Deployer User
  command: credstash -r eu-west-1 get deployer_id_rsa_pub
  register: deployer_key_pub

- user:
    name: deployer

- file:
    path: /home/deployer/.ssh
    state: directory
    owner: deployer
    group: deployer
    mode: 0700

- file:
    path: /home/deployer/.ssh/authorized_keys
    state: touch
    owner: deployer
    group: deployer

