
- user:
    name: deployer

- file:
    path: /home/deployer/.ssh
    state: directory
    owner: deployer
    group: deployer
    mode: 0700

- file:
    path: /home/deployer/.ssh/authorized_keys
    state: touch
    owner: deployer
    group: deployer

- name: Get deployer public key from credstash and place in authorized_keys
  shell: sudo bash -c "credstash -r eu-west-1 get deployer_id_rsa_pub > /home/deployer/.ssh/authorized_keys"
  
- file:
    path: /etc/sudoers.d/sudoers
    state: touch
    owner: root
    group: root

- name: Place sudoers rule for deployer users
  shell: echo '# User rules\ndeployer ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/sudoers
