- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Add sudoers users to wheel group
  user: name=deployer groups=wheel append=yes state=present createhome=yes

# Create .ssh directory in deployer home
- file:
      path: /home/deployer/.ssh
      state: directory
      owner: deployer
      group: deployer
      mode: 0700

# create empty authorized_keys file
- file:
      path: /tmp/authorized_keys
      state: absent


- name: Create Deployer User on Ubuntu
  shell: /usr/local/bin/credstash -r eu-west-1 get ssh/deployer_id_rsa_pub > /tmp/authorized_keys
  ignore_errors: yes

- name: Create Deployer User on Centos
  shell: /usr/bin/credstash -r eu-west-1 get ssh/deployer_id_rsa_pub > /tmp/authorized_keys
  ignore_errors: yes

- copy:
    src: /tmp/authorized_keys
    dest: /home/deployer/.ssh/authorized_keys
    owner: deployer
    group: deployer
    mode: 0700
