- name: Create Deployer User
  command: credstash -r eu-west-1 get deployer_id_rsa_pub
  register: deployer_key_pub

- debug:
   var=deployer_key_pub

- user:
    name: deployer

- file:
    path: /home/deployer/.ssh
    state: directory
    owner: deployer
    group: deployer

- file:
    path: /home/deployer/.ssh/authorized_keys
    owner: deployer
    group: deployer

- name: place public key in authorized_keys
  command: credstash -r eu-west-1 get deployer_id_rsa_pub | > /home/deployer/.ssh/authorized_keys
