environments:
  Ansible:
    pipelines:
      - base
      - nginx-proxy
      - elkstack
      - gocd-ansible
      - ecs-agent-ubuntu-16.04
      - httpd-proxy

pipelines:
  gocd-ansible:
    group: Ansible
    label_template: "${COUNT}"
    materials:
      mygit:
        git: https://github.com/ukparliament/uk.parliament-ansible.git
        branch: master
    timer:
      spec: "*/30 * * * *"
      only_on_changes: no
    stages:
      - build:
          clean_workspace: true
          jobs:
            default:
              tasks:
                - exec:
                    command: ansible-playbook
                    arguments:
                      - gocd-ansible/gocd-ansible-agent.yml
                      - "-f"
                      - 10
  elkstack:
    group: Ansible
    label_template: "${COUNT}"
    materials:
      mygit:
        git: https://github.com/ukparliament/uk.parliament-ansible.git
        branch: master
    stages:
      - build:
          clean_workspace: true
          jobs:
            default:
              tasks:
                - exec:
                    command: ansible-playbook
                    arguments:
                      - elkstack/main-common.yml
                      - "-f"
                      - 10
  base:
    group: Ansible
    label_template: "${COUNT}"
    materials:
      mygit:
        git: https://github.com/ukparliament/uk.parliament-ansible.git
        branch: master
    stages:
      - build:
          clean_workspace: true
          jobs:
            default:
              tasks:
                - exec:
                    command: ansible-playbook
                    arguments:
                      - base/base-common.yml
                      - "-f"
                      - 10

  nginx-proxy:
    group: Ansible
    label_template: "${COUNT}"
    materials:
      mygit:
        git: https://github.com/ukparliament/uk.parliament-ansible.git
        branch: master
    stages:
      - build:
          clean_workspace: true
          jobs:
            default:
              tasks:
                - exec:
                    command: ansible-playbook
                    arguments:
                      - nginx-proxy/nginx-proxy.yml
                      - "-f"
                      - 10


  httpd-proxy:
   group: Ansible
   label_template: "${COUNT}"
   materials:
     mygit:
       git: https://github.com/ukparliament/uk.parliament-ansible.git
       branch: master
   stages:
     - build:
         clean_workspace: true
         jobs:
           default:
             tasks:
               - exec:
                   command: ansible-playbook
                   arguments:
                     - httpd-proxy/httpd-proxy.yml
                     - "-f"
                     - 10

  ecs-agent-ubuntu-16.04:
    group: Packer
    label_template: "${COUNT}"
    materials:
      mygit:
        git: https://github.com/ukparliament/parliament.uk-packer.git
        branch: development
    stages:
      - build:
          clean_workspace: true
          jobs:
            default:
              tasks:
                - exec:
                    command: packer
                    arguments:
                      - build
                      - ecs-agent-ubuntu-16.04.json
