environments:
  Ansible:
    pipelines:
      - elkstack
pipelines:
  elkstack:
    group: Ansible
    label_template: "${COUNT}"
    materials:
      mygit:
        git: https://github.com/ukparliament/uk.parliament-ansible.git
        branch: master
    stages:
      - build:
          clean_workspace: true
          jobs:
            default:
              tasks:
                - exec:
                    command: ansible-playbook
                    arguments:
                      - elkstack/main.yml
                      - "-f"
                      - 10
