environments:
  Ansible:
    pipelines:
      - ecs-agent-ubuntu-16.04
      - base
      - wordpress


pipelines:

  base:
    group: Ansible
    label_template: "${COUNT}"
    materials:
      mygit:
        git: https://github.com/ukparliament/uk.parliament-ansible.git
        branch: master
    timer:
      spec: "0 0/30 * * * ?"
      only_on_changes: no
    stages:
      - build:
          clean_workspace: true
          jobs:
            default:
              tasks:
                - exec:
                    command: ansible-playbook
                    arguments:
                      - base/base-pdswebops.yml
                      - "-f"
                      - 10

  wordpress:
    group: Ansible
    label_template: "${COUNT}"
    materials:
      mygit:
        git: https://github.com/ukparliament/uk.parliament-ansible.git
        branch: master
    stages:
      - build:
          clean_workspace: true
          jobs:
            default:
              tasks:
                - exec:
                    command: ansible-playbook
                    arguments:
                      - wordpress/wordpress.yml
                      - "-f"
                      - 10


  ecs-agent-ubuntu-16.04:
     group: Packer
     label_template: "${COUNT}"
     materials:
       mygit:
         git: https://github.com/ukparliament/parliament.uk-packer.git
         branch: development
     stages:
       - build:
           clean_workspace: true
           jobs:
             default:
               tasks:
                 - exec:
                     command: packer
                     arguments:
                       - build
                       - ecs-agent-ubuntu-16.04.json
