environments:
  Ansible:
    pipelines:
      - base
      - elkstack

pipelines:
  elkstack:
    group: Ansible
    label_template: "${COUNT}"
    materials:
      mygit:
        git: https://github.com/ukparliament/uk.parliament-ansible.git
        branch: master
    stages:
      - build:
          clean_workspace: true
          jobs:
            default:
              tasks:
                - exec:
                    command: ansible-playbook
                    arguments:
                      - elkstack-web1devci/main-web1devci.yml
                      - "-f"
                      - 10
  base:
    group: Ansible
    label_template: "${COUNT}"
    materials:
      mygit:
        git: https://github.com/ukparliament/uk.parliament-ansible.git
        branch: master
    stages:
      - build:
          clean_workspace: true
          jobs:
            default:
              tasks:
                - exec:
                    command: ansible-playbook
                    arguments:
                      - base/base-web1devci.yml
                      - "-f"
                      - 10
