# Install NodeJS

- name: Install the gpg key for nodejs LTS
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present

- name: Install the nodejs LTS repos
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
    state: present
    update_cache: yes

- name: Install nodejs
  apt:
    name: nodejs
    state: present

- name: libreadline-dev
  apt:
    name: libreadline-dev
    state: present

- name: libyaml-dev
  apt:
    name: libyaml-dev
    state: present

- name: libsqlite3-dev
  apt:
    name: libsqlite3-dev
    state: present

- name: sqlite3
  apt:
    name: sqlite3
    state: present

- name: libxml2-dev
  apt:
    name: libxml2-dev
    state: present

- name: libxslt1-dev
  apt:
    name: libxslt1-dev
    state: present

- name: libcurl4-openssl-dev
  apt:
    name: libcurl4-openssl-dev
    state: present

- name: python-software-properties
  apt:
    name: python-software-properties
    state: present

- name: python3-dev
  apt:
    name: python3-dev
    state: present
