---

- name: Add new repository definition to the APT sources configuration directory
  shell: echo "deb https://download.gocd.org /" | sudo tee /etc/apt/sources.list.d/gocd.list
  args:
    creates: gocd.list

- name: Add the GoCD GPG key to APT
  shell: curl  https://download.gocd.org/GOCD-GPG-KEY.asc | apt-key add -
  args:
   chdir: /home/ubuntu/
   creates: GOCD-GPG-KEY.asc



- name: Update Ansible
  shell: apt-add-repository ppa:ansible/ansible

- name: Apt Update
  shell: apt -y update

- name: Install Packages
  apt: state=present name={{ item }}
  with_items:
    - python-pip
    - python-passlib
    - python-setuptools
    - python-dev
    - build-essential
    - default-jre
    - go-server
    - go-agent
    - apache2-utils
    - software-properties-common
    - ansible

# pip install bcrypt for htpasswd
- pip:
    name: bcrypt
- pip:
    name: credstash



- name: Create Directory
  file:
    path: /mnt/artifact-storage
    state: directory
    owner: go
    group: go

- parted:
    device: /dev/xvdh
    number: 1
    state: present

# Format drive
- filesystem:
    fstype: ext4
    dev: /dev/xvdh1

- name: Mount Directory
  mount:
   path: /mnt/artifact-storage
   src: /dev/xvdh1
   fstype: ext4
   opts: defaults
   state: mounted

# add Initial admin user
- name: Get Admin Password
  command: credstash -r eu-west-1 get gocd_admin
  register: gocd_admin

- htpasswd:
    path: /etc/go/gocd-passwd
    name: admin
    password: gocd_admin
    crypt_scheme: bcrypt

# Start up GoCD Server and Agent

- service:
    name: go-server
    state: started

- service:
    name: go-agent
    state: started

- name: place private deployer key in go home directory
  shell: credstash -r eu-west-1 get deployer_id_rsa > /var/go/.ssh/id_rsa

  # Place Python Dynamic Hosts script

- name: Create Inventory Directory
  file:
    path: /etc/ansible/inventory
    state: directory
    owner: root
    group: root

- name: Download ec2.py
  get_url:
    url: https://raw.github.com/ansible/ansible/devel/contrib/inventory/ec2.py
    dest: /etc/ansible/inventory/hosts
    mode: 0755

    # Place ansible.cfg
    - copy:
      src: files/fishballs
      dest: /etc/ansible/fishballs
