# amend freeip virtual hosts file to change proxy_pass http:// to proxy_pass https://

-  lineinfile:
       path: /etc/nginx/sites-available/freeipa.conf
       regexp: 'proxy_pass'
       line: 'proxy_pass https://172.16.40.168;'
   notify:
      - Test nginx and reload

# Add route to web1live subnet for GoCD Server connection

- lineinfile:
       path: /etc/network/interfaces
       line: 'up route add -net 172.16.136.0/24 gw 172.16.40.1'
  notify:
      - Restart networking

# Add route to web1dev subnet for GoCD Server connection

- lineinfile:
       path: /etc/network/interfaces
       line: 'up route add -net 172.16.128.0/24 gw 172.16.40.1'
  notify:
      - Restart networking

# Add route to common ecs private  subnet for nginx proxy connection

- lineinfile:
       path: /etc/network/interfaces
       line: 'up route add -net 172.16.44.0/22 gw 172.16.40.1'
  notify:
      - Restart networking
