- name: Install ntpdate
  package:
    name: ntpdate
    state: latest



- name: Install python*-pip
  package:
    name: python*-pip
    state: latest

- name: Install screen
  package:
    name: screen
    state: latest
- name: Install nano
  package:
    name: nano
    state: latest
- name: Install htop
  package:
    name: htop
    state: latest

- name: Install tree
  package:
    name: tree
    state: latest
- name: Install ncdu
  package:
    name: ncdu
    state: latest
- pip:
    name: credstash
