- name: Install ntpdate
  package:
    name: ntpdate
    state: latest

- name: Install python2-pip
  when: ansible_os_family == "Fedora"
  shell: dnf install python2-pip

- name: Install python27-pip
  when: ansible_os_family == "RedHat"
  shell: yum install python27-pip

- name: Install screen
  package:
    name: screen
    state: latest
- name: Install nano
  package:
    name: nano
    state: latest

- name: Install tree
  package:
    name: tree
    state: latest
- pip:
    name: credstash

- file:
    src: /usr/bin/credstash
    dest: /usr/local/bin/credstash
    state: link

- file:
    src: /usr/bin/credstash.py
    dest: /usr/local/bin/credstash.py
    state: link     
