- shell: sudo su go

- shell: credstash -r eu-west-1 get npm/token
  register: credstash_npm_token
  ignore_errors: yes

- shell: credstash -r eu-west-1 get npm/email
  register: credstash_npm_email
  ignore_errors: yes  

- file:
    path: ~/.npmrc
    state: touch
    owner: go
    group: go
    mode: 0644
