- shell: credstash -r eu-west-1 get npm/email
  register: credstash_npm_email
  ignore_errors: yes  

- file:
    path: ~/.npmrc
    state: touch
    owner: go
    group: go
    mode: 0644
  become_user: go


- name: modify file
  lineinfile:
    path: ~/.npmrc
    line: "{{ credstash_npm_email.stdout }}"
  become_user: go


- name: modify file with new word
  lineinfile:
    path: ~/.npmrc
    line: "blah"
  become_user: go