- shell: credstash -r eu-west-1 get npm/email
  register: credstash_npm_email
  ignore_errors: yes  

- file:
    path: ~/.npmrc
    state: touch
    owner: go
    group: go
    mode: 0644
  become_user: go


- name: modify file
  blockinfile:
    path: ~/.npmrc
    block: |
      {{ credstash_npm_email.stdout }}
  become_user: go

