- shell: credstash -r eu-west-1 get npm/token
  register: credstash_npm_token
  ignore_errors: yes  


- file:
    path: ~/.npmrc
    state: touch
    owner: go
    group: go
    mode: 0644
  become_user: go

- name: modify file with token
  lineinfile:
    path: ~/.npmrc
    line: "//registry.npmjs.org/:_authToken={{ credstash_npm_token.stdout }}"
  become_user: go

