---

- shell: credstash -r eu-west-1 get wordpress/wp_db
  register: wp_db
  ignore_errors: yes  

- shell: credstash -r eu-west-1 get wordpress/wp_db_user
  register: wp_db_user
  ignore_errors: yes  

- shell: credstash -r eu-west-1 get wordpress/wp_db_password
  register: wp_db_password
  ignore_errors: yes  

- shell: credstash -r eu-west-1 get wordpress/auth_key
  register: auth_key
  ignore_errors: yes  

- shell: credstash -r eu-west-1 get wordpress/secure_auth_key
  register: secure_auth_key
  ignore_errors: yes 

- shell: credstash -r eu-west-1 get wordpress/logged_in_key
  register: logged_in_key
  ignore_errors: yes  

- shell: credstash -r eu-west-1 get wordpress/nonce_key
  register: nonce_key
  ignore_errors: yes

- shell: credstash -r eu-west-1 get wordpress/auth_salt
  register: auth_salt
  ignore_errors: yes  

- shell: credstash -r eu-west-1 get wordpress/secure_auth_salt
  register: secure_auth_salt
  ignore_errors: yes  

- shell: credstash -r eu-west-1 get wordpress/logged_in_salt
  register: logged_in_salt
  ignore_errors: yes  

- shell: credstash -r eu-west-1 get wordpress/nonce_salt
  register: nonce_salt
  ignore_errors: yes  



- name: Download WordPress
  get_url: 
    url=https://wordpress.org/latest.tar.gz 
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

- name: Extract WordPress
  unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/ copy=no
  become: yes

- name: Update default Apache site
  become: yes
  lineinfile: 
    dest=/etc/apache2/sites-enabled/000-default.conf 
    regexp="(.)+DocumentRoot /var/www/html"
    line="DocumentRoot /var/www/wordpress"
  notify:
    - restart apache



- name: Wordpress config file
  template:
    src: wp-config.php
    dest: /var/www/wordpress/wp-config.php
    owner: root
  notify: restart apache
