- apt_key:
    url: https://openresty.org/package/pubkey.gpg
    state: present
- apt_repository:
    repo: deb http://openresty.org/package/ubuntu xenial main
    state: present
    update_cache: yes
- apt:
    name: software-properties-common
    state: latest
- apt:
    name: openresty
    state: latest
