- apt_key:
    url: https://openresty.org/package/pubkey.gpg
    state: present
- apt_repository:
    repo: deb http://openresty.org/package/ubuntu xenial main
    state: present
    update_cache: yes
- apt:
    name: software-properties-common
    state: latest
- apt:
    name: openresty
    state: latest
- apt:
    name: apache2-utils
    state: latest

- name: copy nginx basic http authentication config
  copy:
    src: files/nginx_basic_http_authentication.conf
    dest: /usr/local/openresty/nginx/conf/nginx_basic_http_authentication.conf
    owner: root
    group: root
    mode: 0644

- name: Install python-LDAP
  apt:
    name: 'python-ldap'
    state: 'present'
