- apt_key:
    url: https://openresty.org/package/pubkey.gpg
    state: present
- apt_repository:
    repo: deb http://openresty.org/package/ubuntu/dists/xenial main
    state: present
    filename: openresty
    update_cache: yes
-  apt:
    name: software-properties-common
    state: latest
