# pip3 install
- name: install pip3
  apt:
    name: python3-pip
    update_cache: yes

- shell: pip3 install --upgrade google-api-python-client
- shell: pip3 install oauth2client
- shell:  pip3 install apscheduler
- shell: pip3 install --upgrade credstash


- file:
    path: /opt/google-analytics
    state: directory
    owner: root
    group: root
    mode:  0644

- name: copy update-rt python script
  copy:
   src: files/update-rt.py
   dest: /opt/google-analytics/update-rt.py
   owner: root
   group: root
   mode: 0755

- shell: credstash -r eu-west-1 get google-analytics/key
  register: credstash_query_output

- file:
    path: /opt/google-analytics/key.json
    owner: root
    group: root
    mode:  0644
    state: touch

- name: copy Google Analytics key to file
  copy:
    content: "{{ google_analytics_key }}"
    dest: /opt/google-analytics/key.json

- name: copy google-analytics.yaml
  copy:
    src: files/google-analytics.yaml
    dest: /etc/datadog-agent/conf.d/google-analytics.yaml
    owner: dd-agent
    group: dd-agent
    mode: 0644

- name: copy google-analytics.py
  copy:
    src: files/google-analytics.py
    dest: /etc/datadog-agent/checks.d/google-analytics.py
    owner: dd-agent
    group: dd-agent
    mode: 0644

- name: copy update-rt.service
  copy:
    src: files/update-rt.service
    dest: /lib/systemd/system/update-rt.service
    owner: root
    group: root
    mode: 0644

- name: Start update-rt service
  service:
    name: update-rt.service
    state: started
    enabled: yes
