# pip3 install
- name: install pip3
  apt:
    name: python3-pip
    update_cache: yes

- shell: pip3 install --upgrade google-api-python-client
- shell: pip3 install oauth2client
- shell:  pip3 install apscheduler
- shell: pip3 install --upgrade credstash


- file:
    path: /opt/google-analytics
    state: directory
    owner: root
    group: root
    mode:  0644

- name: copy update-rt python script
  copy:
   src: files/update-rt.py
   dest: /opt/google-analytics/update-rt.py
   owner: root
   group: root
   mode: 0755

- shell: credstash -r eu-west-1 get google-analytics/key
  register: credstash_query_output

- file:
    path: /opt/google-analytics/key.json
    owner: root
    group: root
    mode:  0644
    state: touch

- name: copy Google Analytics key to file
  local_action:
    copy:
      content: {{ credstash_query_output}}
      dest: /opt/google-analytics/key.json
