- shell: credstash -r eu-west-1 get freeipa/system_user
  register: credstash_query_output







- name: ECR login
  shell: "$(aws ecr get-login --no-include-email --region eu-west-1)"

- name: Build the image
  command: docker build -t httpd /var/lib/go-agent/pipelines/elkstack/elkstack/files/apache

- name: tqg the image
  command: docker tag httpd:latest 438271037918.dkr.ecr.eu-west-1.amazonaws.com/httpd:latest

- name: push the image
  command: docker push 438271037918.dkr.ecr.eu-west-1.amazonaws.com/httpd:latest
