- hosts: key_core_instances tag_Name_core_bastion_host tag_Name_ecs_bastion_host
  vars:
    freeipa_system_user: "{{credstash_freeipa_output.stdout}}"
    datadog_api_key: "{{credstash_query_output.stdout}}"
    datadog_config:
      hostname: "{{ ec2_tag_Account}}-{{ ec2_tag_Name }}-{{ inventory_hostname}}"
  user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - role: packages-ubuntu
    - role: users
    - role: datadog
    - role: filebeat-ubuntu
    - role: hosts



- hosts: key_ecs_instances:!tag_Name_ecs_node
  vars:
    datadog_api_key: "{{credstash_query_output.stdout}}"
    datadog_config:
      hostname: "{{ ec2_tag_Account}}-{{ ec2_tag_Name }}-{{ inventory_hostname}}"
  user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - role: packages-ubuntu
    - role: users
    - role: datadog
    - role: datadog-docker
    - role: filebeat-ubuntu

- hosts: tag_Name_core-gocd-agent-ansible-1

  roles:
    - role: packer

- hosts: tag_Name_core_bastion_host tag_Name_ecs_bastion_host
  vars:
    freeipa_system_user: "{{credstash_freeipa_output.stdout}}"
  user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - role: freeipa-client

- hosts: tag_Name_core_gocd_agent tag_Name_core_gocd_agent_ansible_1
  vars:
    freeipa_system_user: "{{credstash_freeipa_output.stdout}}"
  user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - role: freeipa-client
    - role: dhcp-revert
