- hosts: common-gocd-server-ansible-1
  user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - role: packages-ubuntu
    - role: users

- hosts: common-freeipa-master-1
  user: fedora
  become: yes
  become_method: sudo

  roles:
    - role: packages-centos
    - role: users
