- hosts: key_core_instances tag_Name_core_bastion_host tag_Name_ecs_bastion_host key_ecs_instances:!tag_Name_ecs_node
  vars:
    freeipa_system_user: "{{credstash_freeipa_output.stdout}}"
    datadog_api_key: "{{credstash_query_output.stdout}}"
    datadog_config:
      hostname: "{{ ec2_tag_Account}}-{{ ec2_tag_Name }}-{{ inventory_hostname}}"
  user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - role: packages-ubuntu
    - role: users
    - role: datadog
    - role: filebeat-ubuntu
    - role: hosts
    - role: freeipa-client



- hosts: tag_Application_second_reading
  user: ubuntu
  become: yes
  become_method: sudo
  roles:
    - role: filebeat-bitnami-wordpress

- hosts: tag_Name_core-gocd-agent-ansible-1

  roles:
    - role: packer
