- hosts: tag_Name_core_gocd_server_ansible_1 core-nginx-proxy-1 key_core_instances tag_Name_core_bastion_host tag_Name_ecs_bastion_host
  vars:
    datadog_api_key: "aaa2b680f8f7b986a18be7de54bb922e"
    datadog_config:
      hostname: "{{ ec2_tag_Account}}-{{ ec2_tag_Name }}-{{ inventory_hostname}}"
  user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - role: packages-ubuntu
    - role: users
    - { role: Datadog.datadog, become: yes }


- hosts: key_ecs_instances
  vars:
    datadog_api_key: "aaa2b680f8f7b986a18be7de54bb922e"
    datadog_config:
      hostname: "{{ ec2_tag_Account}}-{{ ec2_tag_Name }}-{{ inventory_hostname}}"
  user: ec2-user
  become: yes
  become_method: sudo

  roles:
    - role: packages-centos
    - role: users
    - { role: Datadog.datadog, become: yes }



- hosts: tag_Name_core_freeipa_master_1
  vars:
    datadog_api_key: "aaa2b680f8f7b986a18be7de54bb922e"
    datadog_config:
      hostname: "{{ ec2_tag_Account}}-{{ ec2_tag_Name }}-{{ inventory_hostname}}"
  user: fedora
  become: yes
  become_method: sudo

  roles:
     - role: packages-centos
     - role: users
     - { role: Datadog.datadog, become: yes }
