- hosts: tag_Name_core_gocd_server_ansible_1 tag_Name_core_nginx_proxy_1
  user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - role: packages-ubuntu
    - role: users
    - role: datadog-agent

- hosts: tag_Name_core_freeipa_master_1
  user: fedora
  become: yes
  become_method: sudo

  roles:
     - role: packages-centos
     - role: users
     - role: datadog-agent
