- hosts:  common-nginx-proxy-1   key_core_instances:!tag_Name_core_nginx_proxy_1:!tag_Name_core_freeipa_master_1
  vars:
    datadog_api_key: "{{credstash_query_output.stdout}}"
    datadog_config:
      hostname: "{{ ec2_tag_Account}}-{{ ec2_tag_Name }}-{{ inventory_hostname}}"
      expvar_port: 5050
      cmd_port: 5051
  user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - role: packages-ubuntu
    - role: users
    - role: datadog
    - role: filebeat-ubuntu
    - role: hosts



- hosts: core-nginx-proxy-1
  user: ubuntu
  become: yes
  become_method: sudo
  roles:
    - role: filebeat-nginx

- hosts: key_ecs_instances

  vars:
    datadog_api_key: "{{credstash_query_output.stdout}}"
    datadog_config:
      hostname: "{{ ec2_tag_Account}}-{{ ec2_tag_Name }}-{{ inventory_hostname}}"
      expvar_port: 5050
      cmd_port: 5051
  user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - role: packages-ubuntu
    - role: users
    - role: datadog
    - role: datadog-docker



- hosts: tag_Name_core_freeipa_master_1
  vars:
    datadog_api_key: "{{credstash_query_output.stdout}}"
    datadog_config:
      hostname: "{{ ec2_tag_Account}}-{{ ec2_tag_Name }}-{{ inventory_hostname}}"
  user: fedora
  become: yes
  become_method: sudo

  roles:
     - role: packages-centos
     - role: users
     - role: datadog
     - role: filebeat-centos

- hosts: tag_Name_core_gocd_agent_ansible_1
  user: ubuntu
  become: yes
  become_method: sudo
  roles:
    - role: packer

- hosts:  key_ecs_instances:!tag_Name_core_nginx_proxy_1:!tag_Name_core_freeipa_master_1   key_core_instances common-nginx-proxy-1 
  vars:
    freeipa_system_user: "{{credstash_freeipa_output.stdout}}"
  user: ubuntu
  become: yes
  become_method: sudo

  roles:
   - role: freeipa-client
