- hosts: common pdswebops
  user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - role: packages-ubuntu
    - role: users
    - role: datadog-agent

- hosts: common-redhat
  user: fedora
  become: yes
  become_method: sudo

  roles:
     - role: packages-centos
     - role: users
     - role: datadog-agent
