- hosts: tag_Name_core_gocd_server_ansible_1 core-nginx-proxy-1 tag_cluster_elasticsearch_cluster
  vars:
    datadog_api_key: "{{credstash_query_output.stdout}}"
    datadog_config:
      hostname: "{{ ec2_tag_Account}}-{{ ec2_tag_Name }}-{{ inventory_hostname}}"
  user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - role: packages-ubuntu
    - role: users
    - role: datadog


- hosts: key_ecs_instances

  vars:
    datadog_api_key: "{{credstash_query_output.stdout}}"
    datadog_config:
      hostname: "{{ ec2_tag_Account}}-{{ ec2_tag_Name }}-{{ inventory_hostname}}"
  user: ec2-user
  become: yes
  become_method: sudo

  roles:
    - role: packages-centos
    - role: users
    - role: datadog



- hosts: tag_Name_core_freeipa_master_1
  vars:
    datadog_api_key: "{{credstash_query_output.stdout}}"
    datadog_config:
      hostname: "{{ ec2_tag_Account}}-{{ ec2_tag_Name }}-{{ inventory_hostname}}"
  user: fedora
  become: yes
  become_method: sudo

  roles:
     - role: packages-centos
     - role: users
     - role: datadog
     - role: filebeat-centos
