- hosts: common
  user: deployer
  become: yes
  become_method: sudo

  roles:
    - role: packages-ubuntu
    - role: users

- hosts: common-redhat
  become: yes
  become_method: sudo

  roles:
     - role: packages-centos
     - role: users
     - role: datadog-agent
