

- hosts: key_core_instances tag_Name_core_bastion_host tag_Name_ecs_bastion_host
  tasks:
    - shell: credstash -r eu-west-1 get datadog/api_key
      register: checkrun
    - debug:
        var: checkrun
  vars:
    datadog_config:
      hostname: "{{ ec2_tag_Account}}-{{ ec2_tag_Name }}-{{ inventory_hostname}}"
  user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - role: packages-ubuntu
    - role: users
    - { role: Datadog.datadog, become: yes }


- hosts: key_ecs_instances
  tasks:
    - shell: credstash -r eu-west-1 get datadog/api_key
      register: apikey
  vars:
    
    datadog_config:
      hostname: "{{ ec2_tag_Account}}-{{ ec2_tag_Name }}-{{ inventory_hostname}}"
  user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - role: packages-centos
    - role: users
    - { role: Datadog.datadog, become: yes }
