

- hosts: key_core_instances tag_Name_core_bastion_host tag_Name_ecs_bastion_host

  tasks:
    - shell: credstash -r eu-west-1 get datadog/api_key
      register: get_datadog_api_key

  vars:
    datadog_config:
      hostname: "{{ ec2_tag_Account}}-{{ ec2_tag_Name }}-{{ inventory_hostname}}"
      data_dog_api_key: "{{ get_datadog_api_key }}"
  user: ubuntu
  become: yes
  become_method: sudo

  roles:
    - role: packages-ubuntu
    - role: users
    - { role: Datadog.datadog, become: yes }


- hosts: key_ecs_instances

  tasks:
    - shell: /usr/local/bin/credstash -r eu-west-1 get datadog/api_key
      register: datadog_api_key
  vars:
    datadog_config:
      hostname: "{{ ec2_tag_Account}}-{{ ec2_tag_Name }}-{{ inventory_hostname}}"
      data_dog_api_key: "{{ get_datadog_api_key }}"
  user: ec2-user
  become: yes
  become_method: sudo

  roles:
    - role: packages-centos
    - role: users
    - { role: Datadog.datadog, become: yes }
