- name: Update repositories cache and install "docker-ce" package
  apt:
    name: docker-ce
    update_cache: yes

- pip:
    name: awscli

- name: ECR login
  shell: "$(aws ecr get-login --no-include-email --region eu-west-1)"


# Common
- name: Build the image
  command: docker build -t logspout /var/lib/go-agent/pipelines/elkstack/elkstack/files/logspout

- name: tqg the image
  command: docker tag logspout:latest 438271037918.dkr.ecr.eu-west-1.amazonaws.com/logspout:latest

- name: push the image
  command: docker push 438271037918.dkr.ecr.eu-west-1.amazonaws.com/logspout:latest
