- name: ECR login
  shell: "$(aws ecr get-login --no-include-email --region eu-west-1)"

- name: Build the image
  command: docker build -t kibana /var/lib/go-agent/pipelines/elkstack/elkstack/files/kibana

- name: tqg the image
  command: docker tag kibana:latest 438271037918.dkr.ecr.eu-west-1.amazonaws.com/kibana:latest

- name: push the image
  command: docker push 438271037918.dkr.ecr.eu-west-1.amazonaws.com/kibana:latest
