---
vars:
  shortname: "{{ ansible_default_ipv4.address }} {{ ec2_tag_Account}}-{{ ec2_tag_Name }}-{{ inventory_hostname}}.parliament.uk"
- name: Set Hostname with hostname command
  hostname:
    name: "{{ shortname }}"
  notify:
    - restart hostname
    - restart systemd-logind
