---
- name: hosts | Configure Debian
  include: debian.yml
  when: ansible_os_family == 'Debian'

- name: hosts | Configure Redhat
  include: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: hosts | Configure Linux
  include: linux.yml
  when: ansible_system in  [ 'Linux' ]

- name: hosts | Configure Windows
  include: windows.yml
  when: ansible_system in  [ 'Win32NT' ]
