---

- name: Set Hostname with hostname command
  hostname:
    name: "{{ inventory-hostname }}"
  notify:
    - restart hostname
    - restart systemd-logind


- name: Build hosts file (backups will be made)
  lineinfile:
    dest: /etc/hosts
    regexp: "^{{ ansible_default_ipv4.address }}"
    line: "{{ ansible_default_ipv4.address }} {{ hostname }}"
    state: present
    backup: yes
  when: ansible_default_ipv4.address is defined
  notify:
    - restart hostname
    - restart systemd-logind
